### PR TITLE
Do not check block length for api views

### PR DESCRIPTION
**Pull request by arich**
@novu/developers 
Trying to fix code climate failures over here, and I dislike the `"Do not use double quotes when unneeded rule."`

### CODE REVIEW

**Comment by goronfreeman** [comment]
I'm throwing my hat in the ring saying I do like the quotes cop. You can autocorrect only those offenses by combining the `--auto-correct` and `--only` flags. I think it makes the code easier to read and easier to quickly skim.

**Comment by arich** [comment]
Awwww. Okay. 😭 
I mostly find it annoying but as long as one other person wants it in I'm okay to keep it. I just needed to formally bring it up.

**Comment by arich** [comment]
Ignore the misnomer of a branch name then.

**Comment by sebabeceiro** [comment]
I feel the same way as @goronfreeman about the Style/StringLiteral, the Metrics cops are way too strict for my taste and need to be calibrated/disabled accordingly.

**Comment by arich** [comment]
Okay, I backed out the StringLiteral cop removal. Rereview please?

**Pull request merged**
